<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>penpal</name>
  <version>1.0.0</version>
  <description>PenPal: conversational robot arm.</description>
  <maintainer email="cwoodhayes@gmail.com">conorbot</maintainer>
  <license>MIT</license>

  <depend>sensor_msgs</depend>
  <depend>apriltag_msgs</depend>
  <depend>apriltag</depend>
  <depend>image_transport</depend>
  <depend>cv_bridge</depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>ament_xmllint</test_depend>
  <test_depend>python3-pytest</test_depend>

  <exec_depend>apriltag_ros</exec_depend>
  <exec_depend>realsense2_camera</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>penpal_interfaces</exec_depend>
  <exec_depend>realsense2_camera</exec_depend>
  <exec_depend>python3-scipy</exec_depend>
  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>python3-fonttools</exec_depend>
  <exec_depend>python3-pil</exec_depend>
  <exec_depend>python3-skimage</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>shape_msgs</exec_depend>
  <exec_depend>moveit_msgs</exec_depend>
  <exec_depend>moveit_configs_utils</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>ros2launch</exec_depend>
  <exec_depend>std_srvs</exec_depend>
  <exec_depend>example_interfaces</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>franka_msgs</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>rcl_interfaces</exec_depend>
  <!-- <exec_depend>franka_fer_moveit_config</exec_depend> -->
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>tf_transformations</exec_depend>
  <exec_depend>rosidl_runtime_py</exec_depend>

  <exec_depend>camera_ros</exec_depend>
  <exec_depend condition="$ROS_DISTRO != 'humble'">image_proc</exec_depend>
  <exec_depend>image_transport_plugins</exec_depend>

  <!-- IMPORTANT NOTE -->
  <!-- This project additionally requires pytorch and transformers,
   which do not have apt packages. they must be installed to system python
   directly (what we did) or ros2 must be run in a virtualenv. (complicated)
    -->

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>