#!/usr/bin/env python3
"""Standalone test for FontTrajectory (no ROS nodes required).

How to run (from repo root):
    cd penpal_ws/src/final-project-penpal
    python3 penpal/test/test_font_traj.py
"""

import pathlib

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.animation import FuncAnimation

from penpal.font_trajectory import FontTrajectory
from penpal.write_planner import Character


class DummyWriter:
    """Fake WritePlanner for testing FontTrajectory without a robot."""

    def __init__(self) -> None:
        # Will store Character objects generated by FontTrajectory
        self.characters: list[Character] = []

    def write_characters(self, characters: list[Character]) -> None:
        """API-compatible with WritePlanner.write_characters().

        Instead of sending commands to the robot, we just store the characters.
        """
        self.characters.extend(characters)


def plot_characters(characters: list[Character]) -> None:
    """Plot the trajectories of all characters in 2D (x, y).

    Pen-down segments (z > 0) are drawn as solid lines.
    Pen-up segments (z == 0) are skipped.
    """
    fig, ax = plt.subplots()

    for ch in characters:
        traj = ch.trajectory  # (N, 3)
        if traj is None or traj.size == 0:
            continue

        x = traj[:, 0]
        y = traj[:, 1]
        z = traj[:, 2]

        pen_down = z > 0.0
        start_idx = None

        for i in range(len(traj)):
            if pen_down[i]:
                if start_idx is None:
                    start_idx = i
            else:
                if start_idx is not None:
                    ax.plot(x[start_idx:i], y[start_idx:i], "-")
                    start_idx = None

        if start_idx is not None:
            ax.plot(x[start_idx:], y[start_idx:], "-")

        # Mark the start of each character for debugging
        ax.text(
            x[0],
            y[0],
            ch.char,
            fontsize=8,
            color="red",
        )

    ax.set_aspect("equal", "box")
    ax.set_xlabel("x (mm)")
    ax.set_ylabel("y (mm)")
    ax.set_title("FontTrajectory output (virtual board frame)")
    ax.grid(True)
    plt.show()


def plot_flat_path_colored(path: np.ndarray) -> None:
    """Plot a single flattened path, coloring pen-down and pen-up parts.

    Blue  = pen down (z > 0)
    Orange = pen up  (z == 0)
    """
    path = np.asarray(path, dtype=float)
    if path.shape[0] < 2:
        print("Path too short to plot.")
        return

    fig, ax = plt.subplots()
    ax.set_aspect("equal", "box")

    xs = path[:, 0]
    ys = path[:, 1]
    margin = 5.0
    ax.set_xlim(xs.min() - margin, xs.max() + margin)
    ax.set_ylim(ys.min() - margin, ys.max() + margin)
    ax.set_xlabel("x (mm)")
    ax.set_ylabel("y (mm)")
    ax.set_title("Flattened trajectory (blue = pen down, orange = pen up)")
    ax.grid(True)

    down_x, down_y = [], []
    up_x, up_y = [], []
    prev_down: bool | None = None

    for i in range(path.shape[0]):
        x, y, z = path[i]
        is_down = z > 0.0

        if is_down:
            if prev_down is False:
                # Break the up polyline
                up_x.append(np.nan)
                up_y.append(np.nan)
            down_x.append(x)
            down_y.append(y)
        else:
            if prev_down is True:
                # Break the down polyline
                down_x.append(np.nan)
                down_y.append(np.nan)
            up_x.append(x)
            up_y.append(y)

        prev_down = is_down

    ax.plot(
        down_x,
        down_y,
        "-",
        color="tab:blue",
        linewidth=1.5,
        label="pen down",
    )
    ax.plot(
        up_x,
        up_y,
        "-",
        color="tab:orange",
        linewidth=1.5,
        label="pen up",
    )
    ax.legend()
    plt.show()


def animate_flat_path_colored(path: np.ndarray, interval_ms: int = 10) -> None:
    """Animate a flattened path with two colors:

    Blue   = pen down (z > 0)
    Orange = pen up   (z <= 0)
    """
    path = np.asarray(path, dtype=float)
    if path.shape[0] == 0:
        print("Empty path, nothing to animate.")
        return

    fig, ax = plt.subplots()
    ax.set_aspect("equal", "box")

    xs = path[:, 0]
    ys = path[:, 1]
    margin = 5.0
    ax.set_xlim(xs.min() - margin, xs.max() + margin)
    ax.set_ylim(ys.min() - margin, ys.max() + margin)
    ax.set_xlabel("x (mm)")
    ax.set_ylabel("y (mm)")
    ax.set_title("Animated trajectory (blue = pen down, orange = pen up)")
    ax.grid(True)

    down_line, = ax.plot(
        [],
        [],
        "-",
        color="tab:blue",
        linewidth=2,
        label="pen down",
    )
    up_line, = ax.plot(
        [],
        [],
        "-",
        color="tab:orange",
        linewidth=2,
        label="pen up",
    )
    ax.legend()

    down_x, down_y = [], []
    up_x, up_y = [], []
    prev_down: bool | None = None

    def init():
        down_line.set_data([], [])
        up_line.set_data([], [])
        return down_line, up_line

    def update(i: int):
        nonlocal prev_down

        x, y, z = path[i]
        is_down = z > 0.0

        if is_down:
            if prev_down is False:
                # Break the orange polyline when switching up -> down
                up_x.append(np.nan)
                up_y.append(np.nan)
            down_x.append(x)
            down_y.append(y)
        else:
            if prev_down is True:
                # Break the blue polyline when switching down -> up
                down_x.append(np.nan)
                down_y.append(np.nan)
            up_x.append(x)
            up_y.append(y)

        prev_down = is_down

        down_line.set_data(down_x, down_y)
        up_line.set_data(up_x, up_y)
        return down_line, up_line

    _ = FuncAnimation(
        fig,
        update,
        frames=range(path.shape[0]),
        init_func=init,
        interval=interval_ms,
        blit=True,
        repeat=False,
    )

    plt.show()


def main() -> None:
    # 1) Create a dummy writer instead of a real WritePlanner
    writer = DummyWriter()

    # 2) Create FontTrajectory with a config
    cfg = FontTrajectory.Config(
        use_skeleton=False,    # skeleton mode off for now
        skeleton_img_size=512, # used only if use_skeleton=True
    )
    ft = FontTrajectory(writer=writer, cfg=cfg)

    # 3) Register font files (paths are for typical Ubuntu installations)
    font_path = pathlib.Path("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf")
    ft.add_font(font_path)
    font_path = pathlib.Path("/usr/share/fonts/truetype/open-sans/OpenSans-Italic.ttf")
    ft.add_font(font_path)
    font_path = pathlib.Path("/usr/share/fonts/truetype/dejavu/DejaVuSans-ExtraLight.ttf")
    ft.add_font(font_path)
    font_path = pathlib.Path("/usr/share/fonts/truetype/dejavu/DejaVuSansCondensed-Oblique.ttf")
    ft.add_font(font_path)
    font_path = pathlib.Path("/usr/share/fonts/truetype/lato/Lato-HairlineItalic.ttf")
    ft.add_font(font_path)
    font_path = pathlib.Path("/usr/share/fonts/truetype/lato/Lato-ThinItalic.ttf")
    ft.add_font(font_path)

    # 4) Generate trajectories for some text.
    ft.write_text(
        text="ABCDEFGHIJKLMN\nOPQRSTUVWXYZ\nabcdefghijklmn\nopqrstuvwxyz",
        #font_name="DejaVuSans",
        #font_name="OpenSans-Italic",
        #font_name="DejaVuSans-ExtraLight",
        #font_name="DejaVuSansCondensed-Oblique",
        font_name="Lato-HairlineItalic",  # very thin font
        #font_name="Lato-ThinItalic",
        font_size_mm=40.0,
        pen_thickness_mm=1.0,  # currently unused
    )

    print(f"Generated {len(writer.characters)} Character objects.")
    for ch in writer.characters:
        print(repr(ch.char), ch.trajectory.shape)

    # 5) Plot character-wise trajectories (useful for debugging fonts/skeletons).
    plot_characters(writer.characters)

    # 6) Build one continuous, approximately constant-speed path.
    flat_path = ft.build_flat_path_constant_speed(
        writer.characters,
        step_mm=1.0,  # tune if you want finer / coarser sampling
    )

    # Static view: blue = pen down, orange = pen up.
    plot_flat_path_colored(flat_path)

    # Animated view of the same path.
    animate_flat_path_colored(flat_path, interval_ms=10)


if __name__ == "__main__":
    main()
