#!/usr/bin/env python3
"""Standalone test for FontTrajectory (no ROS nodes required).

This script:
  - Creates a dummy WritePlanner-like object (DummyWriter).
  - Uses FontTrajectory to generate trajectories for some text.
  - Plots the resulting trajectories using matplotlib.

How to use: In terminal:
/penpal_ws/src/final-project-penpal$ python3 penpal/test/test_font_traj.py
"""

import pathlib

import matplotlib.pyplot as plt
import numpy as np

from penpal.font_trajectory import FontTrajectory
from penpal.write_planner import Character


class DummyWriter:
    """Fake WritePlanner for testing FontTrajectory without talking to the robot."""

    def __init__(self) -> None:
        # Will store Character objects generated by FontTrajectory
        self.characters: list[Character] = []

    def write_characters(self, characters: list[Character]) -> None:
        """API-compatible with WritePlanner.write_characters().

        Instead of sending commands to the robot, we just store the characters.
        """
        self.characters.extend(characters)


def plot_characters(characters: list[Character]) -> None:
    """Plot the trajectories of all characters in 2D (x, y).

    Pen-down segments (z > 0) are drawn as solid lines.
    Pen-up segments (z == 0) are skipped.
    """
    fig, ax = plt.subplots()

    for ch in characters:
        traj = ch.trajectory  # Nx3
        if traj.size == 0:
            continue

        x = traj[:, 0]
        y = traj[:, 1]
        z = traj[:, 2]

        pen_down = z > 0.0

        start_idx = None
        for i in range(len(traj)):
            if pen_down[i]:
                if start_idx is None:
                    start_idx = i
            else:
                if start_idx is not None:
                    ax.plot(x[start_idx:i], y[start_idx:i], "-")
                    start_idx = None

        if start_idx is not None:
            ax.plot(x[start_idx:], y[start_idx:], "-")

        # Mark the start of each character for debugging
        ax.text(
            x[0],
            y[0],
            ch.char,
            fontsize=8,
            color="red",
        )

    ax.set_aspect("equal", "box")
    ax.set_xlabel("x (mm)")
    ax.set_ylabel("y (mm)")
    ax.set_title("FontTrajectory output (virtual board frame)")
    ax.grid(True)
    plt.show()


def main() -> None:
    # 1) Create a dummy writer instead of a real WritePlanner
    writer = DummyWriter()

    # 2) Create FontTrajectory with default config
    ft = FontTrajectory(writer=writer)

    # 3) Register a font file (Linux example: DejaVuSans)
    font_path = pathlib.Path("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf")
    ft.add_font(font_path)
    font_path = pathlib.Path("/usr/share/fonts/truetype/open-sans/OpenSans-Italic.ttf")
    ft.add_font(font_path)
    font_path = pathlib.Path("/usr/share/fonts/truetype/dejavu/DejaVuSans-ExtraLight.ttf")
    ft.add_font(font_path)
    font_path = pathlib.Path("/usr/share/fonts/truetype/dejavu/DejaVuSansCondensed-Oblique.ttf")
    ft.add_font(font_path)
    font_path = pathlib.Path("/usr/share/fonts/truetype/lato/Lato-HairlineItalic.ttf") 
    ft.add_font(font_path)
    font_path = pathlib.Path("/usr/share/fonts/truetype/lato/Lato-ThinItalic.ttf") 
    ft.add_font(font_path)
    
     
    # 4) Generate trajectories for some text
    #    font_name must match font_path.stem, e.g. "DejaVuSans"
    ft.write_text(
        #text="HELLO\nWORLD",
        text="HELLO\nWORLD",
        #font_name="DejaVuSans",
        #font_name="OpenSans-Italic",
        #font_name="DejaVuSans-ExtraLight",
        #font_name="DejaVuSansCondensed-Oblique",
        #font_name="Lato-HairlineItalic", # This font is very thin!
        font_name="Lato-ThinItalic",

        font_size_mm=40.0,      # approximate letter height in mm
        pen_thickness_mm=1.0,   # currently unused
    )

    print(f"Generated {len(writer.characters)} Character objects.")
    for ch in writer.characters:
        print(repr(ch.char), ch.trajectory.shape)

    # 5) Plot the resulting trajectories
    plot_characters(writer.characters)


if __name__ == "__main__":
    main()
