controller_manager:
  ros__parameters:
    update_rate: 1000  
    cartesian_pose_example_controller:
      type: franka_example_controllers/CartesianPoseExampleController

cartesian_pose_example_controller:
  ros__parameters:
    arm_id: fer
    joint_names:
      - fer_joint1
      - fer_joint2
      - fer_joint3
      - fer_joint4
      - fer_joint5
      - fer_joint6
      - fer_joint7
