"""
Standalone test for FontTrajectory (no ROS nodes required).

How to run (from repo root):
    cd penpal_ws/src/final-project-penpal
    python penpal/penpal/integration_tests/int_test_font_traj.py

To use Hershey fonts, must do pip install Hershey-Fonts.

Commands:
cd ~/penpal_ws
colcon build
source install/setup.bash

cd ~/penpal_ws/src/final-project-penpal
python3 -m venv .venv
source .venv/bin/activate
python -m pip install --upgrade pip
pip install \
  matplotlib \
  numpy \
  fonttools \
  Hershey-Fonts \
  pillow scikit-image

python penpal/penpal/integration_tests/int_test_font_traj.py
"""  # noqa: D213

import pathlib

from matplotlib.animation import FuncAnimation
import matplotlib.pyplot as plt
import numpy as np
from penpal.font_trajectory import FontTrajectory
from penpal.write_planner import Character


class DummyWriter:
    """Fake WritePlanner for testing FontTrajectory without a robot."""

    def __init__(self) -> None:
        """Initialize DummyWriter."""
        # Will store Character objects generated by FontTrajectory
        self.characters: list[Character] = []

    def write_characters(self, characters: list[Character]) -> None:
        """Store the characters."""
        self.characters.extend(characters)


def plot_characters(characters: list[Character]) -> None:
    """
    Plot the trajectories of all characters in 2D (x, y).

    Pen-down segments (z > 0) are drawn as solid lines.
    Pen-up segments (z == 0) are skipped.
    """
    fig, ax = plt.subplots()

    for ch in characters:
        traj = ch.trajectory  # (N, 3)
        if traj is None or traj.size == 0:
            continue

        x = traj[:, 0]
        y = traj[:, 1]
        z = traj[:, 2]

        pen_down = z > 0.0
        start_idx = None

        for i in range(len(traj)):
            if pen_down[i]:
                if start_idx is None:
                    start_idx = i
            else:
                if start_idx is not None:
                    ax.plot(x[start_idx:i], y[start_idx:i], '-')
                    start_idx = None

        if start_idx is not None:
            ax.plot(x[start_idx:], y[start_idx:], '-')

        # Mark the start of each character for debugging
        ax.text(
            x[0],
            y[0],
            ch.char,
            fontsize=8,
            color='red',
        )

    ax.set_aspect('equal', 'box')
    ax.set_xlabel('x (mm)')
    ax.set_ylabel('y (mm)')
    ax.set_title('FontTrajectory output (virtual board frame)')
    ax.grid(True)
    plt.show()


def plot_flat_path_colored(path: np.ndarray) -> None:
    """
    Plot a single flattened path.

    Blue = pen down (z > 0) segments as lines.
    Orange = pen up (z == 0) points as markers (no line).
    """
    path = np.asarray(path, dtype=float)
    if path.shape[0] < 2:
        print('Path too short to plot.')
        return

    fig, ax = plt.subplots()
    ax.set_aspect('equal', 'box')

    xs = path[:, 0]
    ys = path[:, 1]
    margin = 5.0
    ax.set_xlim(xs.min() - margin, xs.max() + margin)
    ax.set_ylim(ys.min() - margin, ys.max() + margin)
    ax.set_xlabel('x (mm)')
    ax.set_ylabel('y (mm)')
    ax.set_title(
        'Flattened trajectory (blue = pen down, orange dots = pen up)'
    )
    ax.grid(True)

    # ----- only draws blue lines at z>0 segments -----
    for i in range(1, path.shape[0]):
        x0, y0, z0 = path[i - 1]
        x1, y1, z1 = path[i]

        # Only draw a line if both ends are pen-down
        if z0 > 0.0 and z1 > 0.0:
            ax.plot([x0, x1], [y0, y1], '-', color='tab:blue', linewidth=1.5)

    # ----- when the pen if off board, use orange dots to show its trail -----
    up_mask = path[:, 2] <= 0.0
    if np.any(up_mask):
        ax.scatter(
            path[up_mask, 0],
            path[up_mask, 1],
            s=5,
            color='tab:orange',
            label='pen up (no line)',
        )

    ax.legend()
    plt.show()


def animate_flat_path_colored(path: np.ndarray, interval_ms: int = 10) -> None:
    """
    Animate a flattened path.

    Blue = pen-down segments (z > 0) drawn as line segments.
    Orange dot = current pen-up position (z <= 0);
                 pen-up segments are not drawn as lines.
    """
    path = np.asarray(path, dtype=float)
    if path.shape[0] == 0:
        print('Empty path, nothing to animate.')
        return

    fig, ax = plt.subplots()
    ax.set_aspect('equal', 'box')

    xs = path[:, 0]
    ys = path[:, 1]
    margin = 5.0
    ax.set_xlim(xs.min() - margin, xs.max() + margin)
    ax.set_ylim(ys.min() - margin, ys.max() + margin)
    ax.set_xlabel('x (mm)')
    ax.set_ylabel('y (mm)')
    ax.set_title('Animated trajectory (blue = pen down, orange dot = pen up)')
    ax.grid(True)

    # One blue line for all pen-down segments, gradually revealed.
    (down_line,) = ax.plot(
        [],
        [],
        '-',
        color='tab:blue',
        linewidth=2,
        label='pen down',
    )
    # One orange marker for the current pen-up position (no orange line).
    (up_marker,) = ax.plot(
        [],
        [],
        'o',
        color='tab:orange',
        markersize=4,
        label='pen up position',
    )
    ax.legend()

    def init():
        down_line.set_data([], [])
        up_marker.set_data([], [])
        return down_line, up_marker

    def update(i: int):
        # Use all points up to frame i, and rebuild the blue polyline
        # using exactly the same rule as in the static plot:
        # draw a line only if both endpoints of the segment have z > 0.
        sub = path[: i + 1]

        down_x: list[float] = []
        down_y: list[float] = []

        for k in range(1, sub.shape[0]):
            x0, y0, z0 = sub[k - 1]
            x1, y1, z1 = sub[k]

            if z0 > 0.0 and z1 > 0.0:
                # Add a tiny segment [ (x0,y0) -> (x1,y1) ], separated by NaN
                # so that non-contiguous segments do not get connected.
                down_x.extend([np.nan, x0, x1])
                down_y.extend([np.nan, y0, y1])

        down_line.set_data(down_x, down_y)

        # Current point: if pen is up, show orange dot at this position;
        # if pen is down, hide the orange marker.
        x_cur, y_cur, z_cur = sub[-1]
        if z_cur <= 0.0:
            up_marker.set_data([x_cur], [y_cur])
        else:
            up_marker.set_data([], [])

        return down_line, up_marker

    _ = FuncAnimation(
        fig,
        update,
        frames=range(path.shape[0]),
        init_func=init,
        interval=interval_ms,
        blit=True,
        repeat=False,
    )

    plt.show()


def main() -> None:
    """Create a dummy WritePlanner for testing."""
    # 1) Create a dummy writer instead of a real WritePlanner
    writer = DummyWriter()

    # 2) Create FontTrajectory with a config
    cfg = FontTrajectory.Config(
        use_skeleton=False,  # skeleton mode off for now
        skeleton_img_size=512,  # used only if use_skeleton=True
    )
    ft = FontTrajectory(writer=writer, cfg=cfg)

    # 3) Register font files (paths are for typical Ubuntu installations)
    font_path = pathlib.Path('/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf')
    ft.add_font(font_path)
    font_path = pathlib.Path(
        '/usr/share/fonts/truetype/open-sans/OpenSans-Italic.ttf'
    )
    ft.add_font(font_path)
    font_path = pathlib.Path(
        '/usr/share/fonts/truetype/dejavu/DejaVuSans-ExtraLight.ttf'
    )
    ft.add_font(font_path)
    font_path = pathlib.Path(
        '/usr/share/fonts/truetype/dejavu/DejaVuSansCondensed-Oblique.ttf'
    )
    ft.add_font(font_path)
    font_path = pathlib.Path(
        '/usr/share/fonts/truetype/lato/Lato-HairlineItalic.ttf'
    )
    ft.add_font(font_path)
    font_path = pathlib.Path(
        '/usr/share/fonts/truetype/lato/Lato-ThinItalic.ttf'
    )
    ft.add_font(font_path)

    # 3b) Register Hershey single-stroke fonts (RECOMMENDED for plotters)
    # Available fonts: futural, scripts, cursive, rowmans, timesi, etc.
    # See FontTrajectory.HERSHEY_FONT_NAMES for full list.
    # Use site https://solhsa.com/hershey/fontprev.html to see pictrues.
    ft.add_hershey_font('futural')  # Simple sans-serif (recommended)
    ft.add_hershey_font('cursive')
    ft.add_hershey_font('scriptc')
    ft.add_hershey_font('music')
    ft.add_hershey_font('rowmant')
    ft.add_hershey_font('astrology')  # fancy font with serif
    ft.add_hershey_font('gothgbt')  # Gothic fancy font.

    # 4) Generate trajectories for some text.
    ft.write_text(
        text='ABCDEFGHIJKLMN\nOPQRSTUVWXYZ\nabcdefghijklmn\nopqrstuvwxyz',
        # font_name="DejaVuSans",
        # font_name="OpenSans-Italic",
        # font_name="DejaVuSans-ExtraLight",
        # font_name="DejaVuSansCondensed-Oblique",
        # font_name="Lato-HairlineItalic",  # very thin font
        # font_name="Lato-ThinItalic",
        # font_name="futural",  # Hershey single-stroke font (RECOMMENDED)
        # font_name="cursive",
        font_name='scriptc',
        # font_name="music",
        # font_name="rowmant",
        # font_name="astrology", # Dude this is fancy.
        # font_name="gothgbt", # Gothic fancy.
        font_size_mm=20.0,
        pen_thickness_mm=1.0,  # currently unused
    )

    print(f'Generated {len(writer.characters)} Character objects.')
    for ch in writer.characters:
        print(repr(ch.char), ch.trajectory.shape)

    # 5) Plot character-wise trajectories (useful for debugging fonts/skeletons).
    plot_characters(writer.characters)

    # 6) Build one continuous, approximately constant-speed path.
    flat_path = ft.build_flat_path_constant_speed(
        writer.characters,
        step_mm=1.0,  # tune if you want finer / coarser sampling
    )

    # Static view: blue = pen down, orange = pen up.
    plot_flat_path_colored(flat_path)

    # Animated view of the same path.
    animate_flat_path_colored(flat_path, interval_ms=10)


if __name__ == '__main__':
    main()
